/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_vincy_regiontextrecognization_MainActivity */

#ifndef _Included_com_example_vincy_regiontextrecognization_MainActivity
#define _Included_com_example_vincy_regiontextrecognization_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_vincy_regiontextrecognization_MainActivity_PERMISSION_CODE_FIRST
#define com_example_vincy_regiontextrecognization_MainActivity_PERMISSION_CODE_FIRST 19L
#ifdef __cplusplus
}
#endif
#endif
