/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wildma_idcardcamera_cropper_CropOverlayView */

#ifndef _Included_com_wildma_idcardcamera_cropper_CropOverlayView
#define _Included_com_wildma_idcardcamera_cropper_CropOverlayView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wildma_idcardcamera_cropper_CropOverlayView
 * Method:    Scan
 * Signature: (Ljava/lang/Object;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_wildma_idcardcamera_cropper_CropOverlayView_Scan
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
